// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx7NzGK2n9PFa-C5gqL6JNk1cXz2vfnmc',
    appId: '1:152540451192:web:2e2fd5dfabcc55a3e1f88d',
    messagingSenderId: '152540451192',
    projectId: 'mine-is-yours-3f2ae',
    authDomain: 'mine-is-yours-3f2ae.firebaseapp.com',
    storageBucket: 'mine-is-yours-3f2ae.appspot.com',
    measurementId: 'G-31RMKDBJRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByp9SuRRPsnjJlgP6f4yKZKzuxGk6QxyY',
    appId: '1:152540451192:android:d6d7b13946b95c8be1f88d',
    messagingSenderId: '152540451192',
    projectId: 'mine-is-yours-3f2ae',
    storageBucket: 'mine-is-yours-3f2ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNJYNHsleIM9-AMmLAmXEtF5ta1lAwnAo',
    appId: '1:152540451192:ios:f1f73e65a2818509e1f88d',
    messagingSenderId: '152540451192',
    projectId: 'mine-is-yours-3f2ae',
    storageBucket: 'mine-is-yours-3f2ae.appspot.com',
    iosClientId: '152540451192-sbliicco0k2bfm66b5g0or64mkabrj9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.musApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNJYNHsleIM9-AMmLAmXEtF5ta1lAwnAo',
    appId: '1:152540451192:ios:f1f73e65a2818509e1f88d',
    messagingSenderId: '152540451192',
    projectId: 'mine-is-yours-3f2ae',
    storageBucket: 'mine-is-yours-3f2ae.appspot.com',
    iosClientId: '152540451192-sbliicco0k2bfm66b5g0or64mkabrj9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.musApp',
  );
}
